#!/bin/bash

if [ x@MCC_SUPPORT@ = xyes ];
then

common_includes="\
-I/home/ryan/mcxx_vanilla/mcxx/nanox-0.14.1 \
-I/home/ryan/mcxx_vanilla/mcxx/nanox-0.14.1/src/core \
-I/home/ryan/mcxx_vanilla/mcxx/nanox-0.14.1/src/apis/c \
-I/home/ryan/mcxx_vanilla/mcxx/nanox-0.14.1/src/pms/openmp \
-I/home/ryan/mcxx_vanilla/mcxx/nanox-0.14.1/src/apis/c \
$END"

VERSIONS="performance debug instrumentation "
PLUGINS="plugins pms arch/unix-os arch/smp arch/gpu"

 debug_CPPFLAGS="-DNANOS_DEBUG_ENABLED ${common_includes} -include "config.h" -include "nanox-config.h"  "
 debug_CXXFLAGS="-O0 -g2 -fno-inline --debug "
 debug_LDFLAGS=" -L/usr/local/cuda/lib64 -Wl,-rpath,/usr/local/cuda/lib64 "
 debug_LIBS=

 instrumentation_CPPFLAGS="-DNANOS_INSTRUMENTATION_ENABLED ${common_includes} -include "config.h" -include "nanox-config.h"  "
 instrumentation_CXXFLAGS="-O3 --instrument "
 instrumentation_LDFLAGS=" -L/usr/local/cuda/lib64 -Wl,-rpath,/usr/local/cuda/lib64 "
 instrumentation_LIBS=

# instrumentation_debug_CPPFLAGS="-DNANOS_DEBUG_ENABLED -DNANOS_INSTRUMENTATION_ENABLED ${common_includes} -include "config.h" -include "nanox-config.h"  "
# instrumentation_debug_CXXFLAGS="-O0 -g2 -fno-inline --instrument --debug "
# instrumentation_debug_LDFLAGS=" -L/usr/local/cuda/lib64 -Wl,-rpath,/usr/local/cuda/lib64 "
# instrumentation_debug_LIBS=

 performance_CPPFLAGS=" ${common_includes} -include "config.h" -include "nanox-config.h"  "
 performance_CXXFLAGS="-O3 "
 performance_LDFLAGS=" -L/usr/local/cuda/lib64 -Wl,-rpath,/usr/local/cuda/lib64 "
 performance_LIBS=

# Common to all versions
cat << EOF
test_CC=
test_CXX=
EOF

# Specific to each version
compile_versions=
for version in performance debug instrumentation ; do
  sh_version=$(tr_sh $version)
  compile_versions+="${sh_version} "
  for libdir in plugins pms arch/unix-os arch/smp arch/gpu core pms apis; do
    library_dir=/home/ryan/mcxx_vanilla/mcxx/nanox-0.14.1/src/${libdir}/${version}/.libs
    eval "${sh_version}_LDFLAGS=\"\
-L${library_dir} -Wl,-rpath,${library_dir} \
\${${sh_version}_LDFLAGS}\""

    eval "${sh_version}_LD_LIBRARY_PATH=\"\
${library_dir}\
\${${sh_version}_LD_LIBRARY_PATH+:}\
\${${sh_version}_LD_LIBRARY_PATH}\""
  done

  eval "${sh_version}_LDFLAGS=\"\
 \
\${${sh_version}_LIBS} \
\${${sh_version}_LDFLAGS}\""

  eval "${sh_version}_ENV=\"
LD_LIBRARY_PATH=\${${sh_version}_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}\""

  cat << EOF
test_CPPFLAGS_${sh_version}="$(eval echo \${${sh_version}_CPPFLAGS} ${test_CPPFLAGS} )"
test_CFLAGS_${sh_version}="$(eval echo \${${sh_version}_CFLAGS} ${test_CFLAGS} -Wno-error )"
test_CXXFLAGS_${sh_version}="$(eval echo \${${sh_version}_CXXFLAGS} ${test_CXXFLAGS} -Wno-error )"
test_LDFLAGS_${sh_version}="$(eval echo \${${sh_version}_LDFLAGS} \${${sh_version}_LIBS} ${test_LDFLAGS})"
test_PLUGINS_${sh_version}="$(eval echo \${${sh_version}_PLUGINS})"
test_ENV_${sh_version}="$(eval echo \${${sh_version}_ENV} ${test_ENV})"
EOF

done # for version

cat << EOF
compile_versions="${compile_versions}"
$(/home/ryan/mcxx_vanilla/mcxx/nanox-0.14.1/tests/gens/config.py $*)
EOF

else

cat <<EOF
test_ignore=yes
EOF

fi

